### ISSUE TITLE
Issues with history and administrator account

### ISSUE THREAD

**Issue by v-sante** [RJ/doorbird-mdns-vlan-subnet-bridge#1]
Got this up and running perfectly so have a local (home-icon) stream etc. in the app. with doorbird in a separate VLAN.  For testing purposes I have no firewall restrictions between doorbird VLAN and main vlan, to rule out any firewall rules issues.

What I'm having difficulty with is that the history of photos of motion/callers disappears.  Trying to login to the administrator account (using saved credentials) results in an error message of "This is not a doorbird device".  I'm wondering if the saved credentials carry with them a saved IP address or similar protection against the credentials being sent to a new IP address.  Was wondering if you had this issue?

Interesting, LAN-only mode makes the whole thing not work (although I am not particularly concerned about that as entirely content not to have it run in LAN-only).

p.s. insofar as it helps:

py running in Raspbian terminal on RPB3+ continuously
Unifi network with specific Doorbird VLAN.  No firewall rules.
iOS doorbird app

**Comment by RJ** [comment]
hmm, i didn't have a problem with the history or motion stuff. that always appeared fine. i was nuking my app install and adding the admin account back each time though, because (iirc) it was remembering the IP or local/cloud preference or something. I was clearing all the app data rather than un/reinstalling, but that does mean you have to create the admin account again.

**Comment by v-sante** [comment]
Thanks - will give that a go and report back.

**Comment by RJ** [comment]
did you solve this?

**Comment by electron23** [comment]
+1 

same here.
